from django.db import models

# Create your models here.
class Delivery(models.Model):
    id = models.AutoField(primary_key=True)  # id
    date = models.DateField(auto_now_add=True)  # 주문일자
    pay_state = models.CharField(default="결제대기", max_length=200)  # 결제상태
    quantity = models.IntegerField()  # 수량
    price = models.FloatField()  # 가격
    buyr_city = models.CharField(max_length=200)  # 주문자 도시
    buyr_country = models.CharField(max_length=200)  # 주문자 국가
    buyr_zipx = models.CharField(max_length=200)  # 주문자 우편번호
    vccode = models.IntegerField(blank=True, null=True)  # 보류
    delivery_state = models.CharField(default="제품준비중", max_length=200)  # 배송 상태
    delivery_num = models.IntegerField(null=True, blank=True)  # 송장번호
    delivery_cost = models.FloatField()  # 배송비
    total_price = models.FloatField()  # 합계 가격 -> 제품가격 + 배송비
    buyr_name = models.CharField(max_length=20)  # 주문자 명
    used_coupon_code = models.ForeignKey(
        "coupon.CouponCode", on_delete=models.SET_NULL, null=True
    )


class ContryCode(models.Model):
    country_idx = models.AutoField(primary_key=True)
    country_code = models.CharField(max_length=200)
    country_dcode = models.CharField(max_length=200)
    country_name = models.CharField(max_length=200)


class DeliveryCost(models.Model):
    id = models.AutoField(primary_key=True)
    quantity = models.IntegerField()
    Australia = models.IntegerField()
    Brazil = models.IntegerField()
    Canada = models.IntegerField()
    China = models.IntegerField()
    France = models.IntegerField()
    Germany = models.IntegerField()
    Hong_kong = models.IntegerField()
    Indonesia = models.IntegerField()
    Japan = models.IntegerField()
    Malaysia = models.IntegerField()
    New_Zealand = models.IntegerField()
    Philippines = models.IntegerField()
    Russia = models.IntegerField()
    Singapore = models.IntegerField()
    Spain = models.IntegerField()
    Taiwan = models.IntegerField()
    Thailand = models.IntegerField()
    UK = models.IntegerField()
    USA = models.IntegerField()
    Vietnam = models.IntegerField()
    Cambodia = models.IntegerField()
    Laos = models.IntegerField()
    Macao = models.IntegerField()
    Mongolia = models.IntegerField()
    Myanmar = models.IntegerField()
    Bangladesh = models.IntegerField()
    Bhutan = models.IntegerField()
    Brunei_Darussala = models.IntegerField()
    India = models.IntegerField()
    Maldives = models.IntegerField()
    Nepal = models.IntegerField()
    Sri_Lanka = models.IntegerField()
    Albania = models.IntegerField()
    Armenia = models.IntegerField()
    Austria = models.IntegerField()
    Azerbaijan = models.IntegerField()
    Bahrain = models.IntegerField()
    Belarus = models.IntegerField()
    Belgium = models.IntegerField()
    Bulgaria = models.IntegerField()
    Bosnia_And_Herzegovina = models.IntegerField()
    Croatia = models.IntegerField()
    Cyprus = models.IntegerField()
    Czech_Rep = models.IntegerField()
    Denmark = models.IntegerField()
    Estonia = models.IntegerField()
    Finland = models.IntegerField()
    Georgia = models.IntegerField()
    Greece = models.IntegerField()
    Hungary = models.IntegerField()
    Iran = models.IntegerField()
    Ireland = models.IntegerField()
    Israel = models.IntegerField()
    Jordan = models.IntegerField()
    Kazakhstan = models.IntegerField()
    Latvia = models.IntegerField()
    Luxembourg = models.IntegerField()
    Macedonia = models.IntegerField()
    Netherlands = models.IntegerField()
    Norway = models.IntegerField()
    Oman = models.IntegerField()
    Pakistan = models.IntegerField()
    Poland = models.IntegerField()
    Portugal = models.IntegerField()
    Qatar = models.IntegerField()
    Romania = models.IntegerField()
    Saudi_Arabia = models.IntegerField()
    Slovakia = models.IntegerField()
    Slovenia = models.IntegerField()
    Sweden = models.IntegerField()
    Switzerland = models.IntegerField()
    Turke = models.IntegerField()
    Ukraine = models.IntegerField()
    United_Arab_Emirates = models.IntegerField()
    Uzbekistan = models.IntegerField()
    Algeria = models.IntegerField()
    Antiless_Netherlands = models.IntegerField()
    Argentina = models.IntegerField()
    Botswana = models.IntegerField()
    Cape_Verde = models.IntegerField()
    Chile = models.IntegerField()
    Costa_Rica = models.IntegerField()
    Cuba = models.IntegerField()
    Djibouti = models.IntegerField()
    Dominican_Republic = models.IntegerField()
    Ecuador = models.IntegerField()
    Egypt = models.IntegerField()
    Eritrea = models.IntegerField()
    Ethiopia = models.IntegerField()
    Fiji = models.IntegerField()
    Kenya = models.IntegerField()
    Lesotho = models.IntegerField()
    Mauritius = models.IntegerField()
    Mexico = models.IntegerField()
    Morocco = models.IntegerField()
    Mozambique = models.IntegerField()
    Nigeria = models.IntegerField()
    Panama = models.IntegerField()
    Peru = models.IntegerField()
    Rwanda = models.IntegerField()
    Tanzania = models.IntegerField()
    Tunisia = models.IntegerField()
    Zambia = models.IntegerField()
    South_Korea = models.IntegerField()
